### ISSUE TITLE
Is this the only support forum?

### ISSUE THREAD

**Issue by suranyami** [Elecrow-RD/CrowPi2#10]
If not, where?

There doesn't seem to be any link to a support forum for CrowPi2 on the elecrow.com site.

Should this (Github repo issues) be where we discuss configuration issues, etc?

**Comment by Elecrow-RD** [comment]
This Github just for fixing the problem that users may encounter when using the CrowPi2.
We intend to provide more ways for users to communicate and communicate. Any news, we will release to our official website: www.elecrow.com

**Comment by Pearl-852** [comment]
Just for record, an official forum is now online at
[forum.elecrow.com/categories/Raspberry-Pi-CrowPi](https://forum.elecrow.com/categories/Raspberry-Pi-CrowPi)
