### ISSUE TITLE
Keyboard and Mouse won't pair

### ISSUE THREAD

**Issue by 716green** [Elecrow-RD/CrowPi2#17]
After following all of the instructions here in this repo, online on other resources, and the instructions in the manual, there's no progress linking the keyboard or mouse. Unable to reach any support associates.

**Comment by Elecrow-RD** [comment]
> After following all of the instructions here in this repo, online on other resources, and the instructions in the manual, there's no progress linking the keyboard or mouse. Unable to reach any support associates.

My workmate Emma has contacted you and will help you to solve the problem. Thank you!
