### ISSUE TITLE
Wifi Connection issues

### ISSUE THREAD

**Issue by VamsiDevalla** [Elecrow-RD/CrowPi2#2]
**Not able to connect to wifi.**
Steps to reproduce:
1. Click the network  icon
2. Click on the network name
3. Enter the password for the network
4. Click on OK/press enter

After multiple retries, the icon will change to indicate that it's connected to the internet but when the user visits the browser and searches for something. it says the internet is not connected.

**Comment by Elecrow-RD** [comment]
Try to follow the steps below to determine the problem:

1. Make sure your wifi can access the internet
2. Open the terminal and type the  command below to see if the CrowPi2 can get the IP address:
           ifconfig
3. If still cannot access the network, try to open your cell phone hotspot. Use CrowPi2 to connect the hotspot and then see if CrowPi2 can access the network
