### ISSUE TITLE
Pull Request did not merge the "About' section.

### ISSUE THREAD

**Issue by Pearl-852** [Elecrow-RD/CrowPi2#44]
It seems that the informations in the About did not get merged, so you may want to add it in manually as shown below,
![About](https://user-images.githubusercontent.com/74016222/111578730-a7f95180-87ef-11eb-8a7d-699a8c382601.png)

### Edit repository details
**Description**  
CrowPi2 - Raspberry Pi Laptop & STEM Learning Platform  

**Website**
https://www.elecrow.com/crowpi2-raspberry-pi-portable-laptop.html

**Comment by Elecrow-RD** [comment]
Thanks~

**Comment by Pearl-852** [comment]
Just checked your repo, but it hasn't been updated yet.  
![2021-03-20-131758_291x174_scrot](https://user-images.githubusercontent.com/74016222/111859870-ef621800-897e-11eb-9976-f68739c6cf3e.png)
