### ISSUE TITLE
Stuck on Boot screen

### ISSUE THREAD

**Issue by suranyami** [Elecrow-RD/CrowPi2#9]
Hi. Just got the CrowPi2. Assembly was easy.

Booting up on the supplied microSD card, I get as far as the Boot screen and then it freezes.

I'm guessing I should just try re-burning the SD card, then?

![crowpi2-boot-screen](https://user-images.githubusercontent.com/69984/100689663-fb7a9780-33d8-11eb-8029-9084d4ea5f3b.png)

**Comment by Elecrow-RD** [comment]
Please re-write the latest image in your micro-SD card and try it out.
